--- # Config file, to hold values for publication document

# The key-value pairs in this YAML config file provide
# details to be read in and used in the RMarkdown template
# for the QPI summary publication

# See https://learnxinyminutes.com/docs/yaml/
# ... and https://rstudio.github.io/config/articles/introduction.html 

# TSG - remember to set the TSG value separately in housekeeping.R 
# when running the scripts to update hb_hosp etc

tsg: "Endometrial"

authors: 
  - "Garry Hecht | Principal Information Analyst"
  - "Pauline Ward | Information Analyst"
  
